site_name: My App Documentation
site_description: Hướng dẫn sử dụng và tài liệu cho ứng dụng
theme:
  name: material
  language: vi
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Trang chủ: index.md
  - Hướng dẫn sử dụng:
    - Bắt đầu: user-guide/getting-started.md
    - Tính năng chính: user-guide/features.md
    - Cài đặt: user-guide/settings.md
    - Câu hỏi thường gặp: user-guide/faq.md
  - Tài liệu kỹ thuật:
    - Yêu cầu hệ thống: technical/requirements.md
    - Cài đặt ứng dụng: technical/installation.md
    - Xử lý sự cố: technical/troubleshooting.md
  - Cập nhật & Phiên bản: changelog.md
  - Liên hệ & Hỗ trợ: support.md

plugins:
  - search:
      lang: vi
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YourUsername/YourRepo
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/YourPage
