site_name: Go Shopping
site_description: Hướng dẫn sử dụng và tài liệu cho ứng dụng

theme:
  name: material
  language: vi
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Trang chủ: index.md
  - Hướng dẫn sử dụng:
    - Tài khoản:
      - Đăng nhập: user-guide/account/login.md
      - Đăng ký: user-guide/account/register.md
      - Quên mật khẩu: user-guide/account/forgot-password.md
    - Thông tin cá nhân:
      - Xem thông tin: user-guide/profile/view.md
      - Chỉnh sửa thông tin: user-guide/profile/edit.md
      - Đổi mật khẩu: user-guide/profile/change-password.md
    - Nhóm:
      - Xem danh sách nhóm: user-guide/group/home.md
      - Tạo nhóm: user-guide/group/add-group.md
      - Thêm thành viên: user-guide/group/add-member.md
    - Thống kê & Thông báo:
      - Xem thống kê: user-guide/stats/view.md
      - Thông báo: user-guide/notification/list_noti.md
    - Quản lý thực phẩm:
      - Phân loại thực phẩm: user-guide/food/categories.md
      - Quản lý công thức nấu ăn: user-guide/recipes/list.md
      - Quản lý thực phẩm:
        - Danh sách thực phẩm: user-guide/food/items/list.md
        - Thêm thực phẩm mới: user-guide/food/items/add.md
        - Chỉnh sửa thực phẩm: user-guide/food/items/edit.md
      - Quản lý nhiệm vụ:
        - Danh sách nhiệm vụ: user-guide/food/tasks/list.md
        - Giao nhiệm vụ mua đồ mới: user-guide/food/tasks/new-item.md
        - Giao nhiệm vụ mua đồ cũ: user-guide/food/tasks/restock.md
      - Quản lý bữa ăn:
        - Xem kế hoạch: user-guide/food/meal-plan/view.md
        - Lập kế hoạch: user-guide/food/meal-plan/create.md

  - Tài liệu kỹ thuật:
    - Yêu cầu hệ thống: technical/requirements.md
    - Cài đặt ứng dụng: technical/installation.md
    - Xử lý sự cố: technical/troubleshooting.md
  - Cập nhật & Phiên bản: changelog.md
  - Liên hệ & Hỗ trợ: support.md

plugins:
  - search:
      lang: vi
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/YourUsername/YourRepo
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/YourPage
